export interface SearchKeyword {
  slug: string
  type: 'tegevusala' | 'seeria'
  parentSlug?: string
}

export const SEARCH_KEYWORDS: Record<string, SearchKeyword> = {
  'aiapump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'aiapumbad': { slug: 'veeautomaadid', type: 'tegevusala' },
  'kastmispump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'kasvuhoonepump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'kasvuhoone pump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'greenhouse pump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'garden pump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'garden watering': { slug: 'veeautomaadid', type: 'tegevusala' },
  'watering pump': { slug: 'veeautomaadid', type: 'tegevusala' },
  'irrigation': { slug: 'veeautomaadid', type: 'tegevusala' },
  'садовый насос': { slug: 'veeautomaadid', type: 'tegevusala' },
  'полив': { slug: 'veeautomaadid', type: 'tegevusala' },
  'dārza sūknis': { slug: 'veeautomaadid', type: 'tegevusala' },
  'laistīšana': { slug: 'veeautomaadid', type: 'tegevusala' },
  'sodo siurblys': { slug: 'veeautomaadid', type: 'tegevusala' },
  'laistymas': { slug: 'veeautomaadid', type: 'tegevusala' },
  'veeauatomaat': { slug: 'veeautomaadid', type: 'tegevusala' },
  'hüdrofoor': { slug: 'veeautomaadid', type: 'tegevusala' },
  'hydropneumatic': { slug: 'veeautomaadid', type: 'tegevusala' },
  'hydrofor': { slug: 'veeautomaadid', type: 'tegevusala' },
  'hydrofoor': { slug: 'veeautomaadid', type: 'tegevusala' },
  'küte': { slug: 'kuttepumbad', type: 'tegevusala' },
  'heating': { slug: 'kuttepumbad', type: 'tegevusala' },
  'radiator': { slug: 'kuttepumbad', type: 'tegevusala' },
  'circulation pump': { slug: 'kuttepumbad', type: 'tegevusala' },
  'отопление': { slug: 'kuttepumbad', type: 'tegevusala' },
  'circulation': { slug: 'kuttepumbad', type: 'tegevusala' },
  'tarbevesi': { slug: 'tsirkulatsioonipumbad-soe-tarbevesi', type: 'tegevusala' },
  'hot water': { slug: 'tsirkulatsioonipumbad-soe-tarbevesi', type: 'tegevusala' },
  'boiler': { slug: 'tsirkulatsioonipumbad-soe-tarbevesi', type: 'tegevusala' },
  'dhw': { slug: 'tsirkulatsioonipumbad-soe-tarbevesi', type: 'tegevusala' },
  'puurkaev': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'borewell': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'borehole': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'deep well': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'submersible': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'kaevupump': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'kaevu pump': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'süvapump': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'süvapuurauk': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'скважина': { slug: 'puurkaevupumbad', type: 'tegevusala' },
  'drenaaž': { slug: 'drenaazipumbad', type: 'tegevusala' },
  'drainage': { slug: 'drenaazipumbad', type: 'tegevusala' },
  'flood': { slug: 'drenaazipumbad', type: 'tegevusala' },
  'cellar': { slug: 'drenaazipumbad', type: 'tegevusala' },
  'дренаж': { slug: 'drenaazipumbad', type: 'tegevusala' },
  'salvkaev': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'salvkaevupump': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'salvkaevu pump': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'well': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'shallow well': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'surface pump': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'колодец': { slug: 'salvkaevupumbad', type: 'tegevusala' },
  'rõhutõste': { slug: 'rohutostepumbad', type: 'tegevusala' },
  'pressure booster': { slug: 'rohutostepumbad', type: 'tegevusala' },
  'booster pump': { slug: 'rohutostepumbad', type: 'tegevusala' },
  'low water pressure': { slug: 'rohutostepumbad', type: 'tegevusala' },
  'повышение давления': { slug: 'rohutostepumbad', type: 'tegevusala' },
  'reovesi': { slug: 'reoveepumbad', type: 'tegevusala' },
  'sewage': { slug: 'reoveepumbad', type: 'tegevusala' },
  'wastewater': { slug: 'reoveepumbad', type: 'tegevusala' },
  'fecal': { slug: 'reoveepumbad', type: 'tegevusala' },
  'kanalisatsioon': { slug: 'reoveepumbad', type: 'tegevusala' },
  'канализация': { slug: 'reoveepumbad', type: 'tegevusala' },
  // Product series names — mapped to their series page URL with parent category
  'hydrojet': { slug: 'grundfos-cmb', type: 'seeria', parentSlug: 'rohutostepumbad' },
  'cmb': { slug: 'grundfos-cmb', type: 'seeria', parentSlug: 'rohutostepumbad' },
  'unilift': { slug: 'grundfos-unilift', type: 'seeria', parentSlug: 'drenaazipumbad' },
  'unlift': { slug: 'grundfos-unilift', type: 'seeria', parentSlug: 'drenaazipumbad' },
  'unitlift': { slug: 'grundfos-unilift', type: 'seeria', parentSlug: 'drenaazipumbad' },
  'jp': { slug: 'grundfos-jp', type: 'seeria', parentSlug: 'salvkaevupumbad' },
  'grundfos jp': { slug: 'grundfos-jp', type: 'seeria', parentSlug: 'salvkaevupumbad' },
  'sba': { slug: 'grundfos-sba', type: 'seeria', parentSlug: 'reoveepumbad' },
  'seg': { slug: 'grundfos-seg', type: 'seeria', parentSlug: 'reoveepumbad' },
  'scala': { slug: 'grundfos-scala', type: 'seeria', parentSlug: 'veeautomaadid' },
  'skala': { slug: 'grundfos-scala', type: 'seeria', parentSlug: 'veeautomaadid' },
  'skaala': { slug: 'grundfos-scala', type: 'seeria', parentSlug: 'veeautomaadid' },
  'scala1': { slug: 'grundfos-scala', type: 'seeria', parentSlug: 'veeautomaadid' },
  'scala2': { slug: 'grundfos-scala2', type: 'seeria', parentSlug: 'veeautomaadid' },
  'scala 2': { slug: 'grundfos-scala2', type: 'seeria', parentSlug: 'veeautomaadid' },
  'sq': { slug: 'grundfos-sq', type: 'seeria', parentSlug: 'puurkaevupumbad' },
  'grundfos sq': { slug: 'grundfos-sq', type: 'seeria', parentSlug: 'puurkaevupumbad' },
  'sp': { slug: 'grundfos-sp', type: 'seeria', parentSlug: 'puurkaevupumbad' },
  'cr': { slug: 'grundfos-cr', type: 'seeria', parentSlug: 'puurkaevupumbad' },
  'magn': { slug: 'grundfos-magna', type: 'seeria', parentSlug: 'kuttepumbad' },
  'magna': { slug: 'grundfos-magna', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alpha': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alfa': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alpha1': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alpha2': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alpha3': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'alpha 2': { slug: 'grundfos-alpha', type: 'seeria', parentSlug: 'kuttepumbad' },
  'tp': { slug: 'grundfos-tp', type: 'seeria', parentSlug: 'kuttepumbad' },
}

export function matchSearchKeyword(query: string): SearchKeyword | null {
  const normalized = query.trim().toLowerCase().replace(/-/g, ' ')
  return SEARCH_KEYWORDS[normalized] ?? null
}
